### ISSUE TITLE
Cassandra 3.7

### ISSUE THREAD

**Issue by ostojicmilica** [wunzeco/ansible-cassandra#1]
Is it possible to install latest version cassandra with your role and how?

**Comment by wunzeco** [comment]
@ostojicmilica Thanks for reaching out. I hope you should be able to but please give me a couple of hours to test it out myself and get back to you.

**Comment by wunzeco** [comment]
@ostojicmilica 

Apologies that it took a lot longer to get back to you. You'd be pleased to know that I've made cassandra 3.7.0 the default for the role. 

Indeed v2.2.5 seems really old. So if you want to use the latest version of cassandra with the role, this is what you could do

```
 - hosts: dbhost

  vars:
    cassandra_version: 3.7.0
    cassandra_cluster_name: myAwesomeCluster
    cassandra_seeds: [ "seedIp1", "seedIp2" ]                   # List of IP Addresses ONLY
    cassandra_listen_address: "{{ ansible_eth0.ipv4.address }}"
    cassandra_rpc_address: "{{ ansible_eth0.ipv4.address }}"

  roles:
    - wunzeco.cassandra
```

In a cloud environment, it is easier to work with host FQDNs than IPs because IP addresses change. So you could also specify `cassandra_seeds_fqdns` in place of `cassandra_seeds`. This is how I configure my cassandra cluster

```
  vars:
    java_package: oracle-java8-installer
    cassandra_version: 3.7.0
    cassandra_cluster_name: myAwesomeCluster
    cassandra_seeds_fqdns:
      - cassandra0.dev.example.internal
      - cassandra1.dev.example.internal

  roles:
    - wunzeco.java
    - wunzeco.cassandra
```

I hope this helps.

If you have any comments or improvements please do not hesitate to let me know.
